repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file BackEnd/config/.isort.cfg .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config BackEnd/config/.black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config BackEnd/config/.flake8 .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: pip-freeze
        name: Update requirements.txt
        entry: bash -c 'pip freeze > requirements.txt'
        language: system
        types: [ python ]
        pass_filenames: false

